/**
 * Seed script for Cavalli Vibe Quest
 * Reconciles with live catalog and seeds an editable draft configuration.
 */
import { MongoClient } from 'mongodb';
import { VibeQuestConfig, VibeQuestQuestion } from '../modules/vibe-quest/vibe-quest.types';
import { VibeQuestEngine } from '../modules/vibe-quest/vibe-quest.engine';

const uri = process.env.MONGODB_URI || 'mongodb+srv://sandip2nepal_db_user:jzKRgGtGJpU9jhR7@cluster0.tkcmyix.mongodb.net/benzin_saas_db?retryWrites=true&w=majority';
const RID = 'RES_EED4E9D266DF';

export function buildCavalliVibeQuestQuestions(): VibeQuestQuestion[] {
  return [
    /* ═══════════════ HOOKAH STAGE ═══════════════ */
    {
      id: 'q_hookah_mood',
      stage: 'hookah',
      title: 'Hookah Vibe',
      question_text: "What’s the vibe tonight? 💨",
      helper_text: "Pick the mood that fits your night",
      emoji: '💨',
      type: 'single_select',
      active: true,
      sort_order: 1,
      required: false,
      skippable: true,
      repeat_policy: 'show_once',
      default_destination: { type: 'question', ref_id: 'q_hookah_flavor' },
      branches: [],
      answers: [
        {
          id: 'ans_h_sweet',
          label: 'Sweet & fruity',
          emoji: '🍓',
          description: 'Lush berries, sweet peaches & refreshing tropical notes',
          active: true,
          sort_order: 1,
          signals: ['fruity', 'sweet'],
          destination: { type: 'question', ref_id: 'q_hookah_flavor' },
        },
        {
          id: 'ans_h_minty',
          label: 'Fresh & minty',
          emoji: '❄️',
          description: 'Crisp spearmint, icy chill & refreshing citrus-mint',
          active: true,
          sort_order: 2,
          signals: ['minty', 'fresh'],
          destination: { type: 'question', ref_id: 'q_hookah_flavor' },
        },
        {
          id: 'ans_h_cozy',
          label: 'Cozy & familiar',
          emoji: '☕',
          description: 'Warm spiced chai and creamy rich undertones',
          active: true,
          sort_order: 3,
          signals: ['chai', 'creamy', 'cozy'],
          pinned_product_ids: ['MI_kashmiri_chai_hookah'],
          destination: { type: 'question', ref_id: 'q_hookah_path' },
        },
        {
          id: 'ans_h_bold',
          label: 'Bold & adventurous',
          emoji: '🔥',
          description: 'Distinctive, multi-layered signature blends',
          active: true,
          sort_order: 4,
          signals: ['bold', 'adventurous'],
          pinned_product_ids: ['MI_zaalim_hookah', 'MI_dragon_hookah'],
          destination: { type: 'question', ref_id: 'q_hookah_path' },
        },
        {
          id: 'ans_h_creamy',
          label: 'Smooth & creamy',
          emoji: '🥛',
          description: 'Silky smooth clouds with vanilla and rich finish',
          active: true,
          sort_order: 5,
          signals: ['creamy', 'smooth'],
          pinned_product_ids: ['MI_white_king_hookah', 'MI_anarkali_hookah'],
          destination: { type: 'question', ref_id: 'q_hookah_path' },
        },
        {
          id: 'ans_h_surprise',
          label: 'Surprise me',
          emoji: '🎲',
          description: "We'll highlight our best signature house mixes",
          active: true,
          sort_order: 6,
          signals: ['variety'],
          pinned_product_ids: ['MI_cavalli_crush_hookah', 'MI_dubai_nights_hookah', 'MI_habibi_nights_hookah'],
          destination: { type: 'question', ref_id: 'q_hookah_path' },
        },
      ],
    },
    {
      id: 'q_hookah_flavor',
      stage: 'hookah',
      title: 'Flavor Refinement',
      question_text: 'How do you like your flavor? 🌿',
      helper_text: 'Choose a flavor direction to narrow your blend',
      emoji: '🌿',
      type: 'single_select',
      active: true,
      sort_order: 2,
      required: false,
      skippable: true,
      repeat_policy: 'show_once',
      default_destination: { type: 'question', ref_id: 'q_hookah_path' },
      answers: [
        {
          id: 'ans_hf_sweet',
          label: 'Sweet',
          emoji: '🍬',
          active: true,
          sort_order: 1,
          signals: ['sweet'],
          destination: { type: 'question', ref_id: 'q_hookah_path' },
        },
        {
          id: 'ans_hf_tangy',
          label: 'Tangy',
          emoji: '🍋',
          active: true,
          sort_order: 2,
          signals: ['citrus', 'tangy'],
          destination: { type: 'question', ref_id: 'q_hookah_path' },
        },
        {
          id: 'ans_hf_minty',
          label: 'Minty',
          emoji: '🌿',
          active: true,
          sort_order: 3,
          signals: ['minty'],
          destination: { type: 'question', ref_id: 'q_hookah_path' },
        },
        {
          id: 'ans_hf_tropical',
          label: 'Tropical',
          emoji: '🥭',
          active: true,
          sort_order: 4,
          signals: ['tropical'],
          destination: { type: 'question', ref_id: 'q_hookah_path' },
        },
        {
          id: 'ans_hf_complex',
          label: 'Complex blend',
          emoji: '🌀',
          active: true,
          sort_order: 5,
          signals: ['complex', 'bold'],
          destination: { type: 'question', ref_id: 'q_hookah_path' },
        },
        {
          id: 'ans_hf_dealers',
          label: "Dealer's choice",
          emoji: '🤷',
          active: true,
          sort_order: 6,
          signals: ['variety'],
          destination: { type: 'question', ref_id: 'q_hookah_path' },
        },
      ],
    },
    {
      id: 'q_hookah_path',
      stage: 'hookah',
      title: 'Mix Style',
      question_text: 'House mix or build your own? 🧪',
      helper_text: 'Pick a signature house blend or craft your own bowl in Custom Mix Lab',
      emoji: '🧪',
      type: 'single_select',
      active: true,
      sort_order: 3,
      required: false,
      skippable: true,
      repeat_policy: 'show_once',
      recommendation_config: {
        result_count: 3,
        eligible_category_ids: ['CAT_HOOKAH_HOUSE_MIXES'],
      },
      answers: [
        {
          id: 'ans_hp_signature',
          label: 'Keep it signature',
          emoji: '👑',
          description: 'Cavalli house blends ($35)',
          active: true,
          sort_order: 1,
          signals: ['house_mix'],
          pinned_product_ids: [
            'MI_cavalli_crush_hookah',
            'MI_habibi_nights_hookah',
            'MI_dubai_nights_hookah',
            'MI_shah_jahan_hookah',
            'MI_anarkali_hookah',
            'MI_white_king_hookah',
          ],
          destination: { type: 'category', ref_id: 'CAT_HOOKAH_HOUSE_MIXES' },
        },
        {
          id: 'ans_hp_lab',
          label: 'Let me create my own',
          emoji: '🧪',
          description: 'Mix up to 5 custom flavors with percentage balance',
          active: true,
          sort_order: 2,
          signals: ['custom_mix'],
          destination: { type: 'custom_mix_lab' },
        },
        {
          id: 'ans_hp_both',
          label: 'Show me both',
          emoji: '🎯',
          description: 'Browse top house mixes and try the Mix Lab',
          active: true,
          sort_order: 3,
          signals: ['variety'],
          pinned_product_ids: ['MI_cavalli_crush_hookah', 'MI_dubai_nights_hookah'],
          destination: { type: 'recommendations' },
        },
      ],
    },
    {
      id: 'q_hookah_extras',
      stage: 'hookah',
      title: 'Hookah Extras',
      question_text: 'Want to customize your setup? ❄️',
      helper_text: 'Optional upgrades for an ultra-chilled session',
      emoji: '❄️',
      type: 'single_select',
      active: true,
      sort_order: 4,
      required: false,
      skippable: true,
      repeat_policy: 'show_once',
      display_conditions: [
        { operator: 'cart_has_category', field: 'CAT_HOOKAH_HOUSE_MIXES' },
      ],
      answers: [
        {
          id: 'ans_he_classic',
          label: 'Classic setup',
          emoji: '🌬️',
          description: 'Standard session setup',
          active: true,
          sort_order: 1,
          signals: [],
          destination: { type: 'next_stage', ref_id: 'food' },
        },
        {
          id: 'ans_he_refill',
          label: 'Head refill ($10)',
          emoji: '🔄',
          description: 'Fresh bowl packed for later',
          active: true,
          sort_order: 2,
          signals: ['refill'],
          pinned_product_ids: ['MI_head_refill_hookah'],
          conditions: [
            { operator: 'cart_not_has_product', field: 'PKG_DAKU' },
          ],
          destination: { type: 'product', ref_id: 'MI_head_refill_hookah' },
        },
        {
          id: 'ans_he_none',
          label: "I'm good, let's look at food",
          emoji: '👍',
          active: true,
          sort_order: 3,
          signals: [],
          destination: { type: 'next_stage', ref_id: 'food' },
        },
      ],
    },

    /* ═══════════════ FOOD STAGE ═══════════════ */
    {
      id: 'q_food_craving',
      stage: 'food',
      title: 'Food Craving',
      question_text: 'What are we craving? 🍽️',
      helper_text: 'Tell us what hits the spot right now',
      emoji: '🍽️',
      type: 'single_select',
      active: true,
      sort_order: 1,
      required: false,
      skippable: true,
      repeat_policy: 'show_once',
      default_destination: { type: 'recommendations' },
      recommendation_config: {
        result_count: 4,
        diversity_limit_per_category: 2,
      },
      answers: [
        {
          id: 'ans_fc_desi',
          label: 'Desi & Pakistani',
          emoji: '🥙',
          description: 'Biryani, kabobs & traditional slow-cooked comfort',
          active: true,
          sort_order: 1,
          signals: ['desi', 'pakistani'],
          pinned_product_ids: [
            'MI_chicken_dum_biryani_main',
            'MI_chicken_boti_main',
            'ITM_9CD79FD00822', // Sizzling Gola Kabob
            'MI_daal_chawal_veg',
            'MI_beef_koobideh_main',
          ],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_fc_grill',
          label: 'Straight from the grill',
          emoji: '🔥',
          description: 'Charcoal-grilled skewers, koobideh & lamb chops',
          active: true,
          sort_order: 2,
          signals: ['grilled'],
          pinned_product_ids: [
            'MI_beef_koobideh_main',
            'MI_chicken_boti_main',
            'MI_chicken_kabob_main',
            'MI_lamb_chops_main',
            'ITM_C651EACD4115', // Malai Chicken Boti
          ],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_fc_burger',
          label: 'Burger or wrap',
          emoji: '🍔',
          description: 'Smashed beef, crispy zinger & paratha rolls',
          active: true,
          sort_order: 3,
          signals: ['burger', 'wrap'],
          pinned_product_ids: [
            'MI_beef_smash_burger',
            'MI_chicken_zinger_burger',
            'MI_shawarma_wrap',
            'MI_mirchi_paratha_roll',
            'MI_dynamite_chicken_wrap',
          ],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_fc_indochinese',
          label: 'Indo-Chinese & street food',
          emoji: '🍜',
          description: 'Wok-tossed chili chicken, noodles & steamed momos',
          active: true,
          sort_order: 4,
          signals: ['indochinese', 'street_food'],
          pinned_product_ids: [
            'MI_chili_chicken_cont',
            'MI_mongolian_chicken_cont',
            'MI_chow_mein_cont',
            'MI_momo_cont',
            'MI_kung_pao_chicken_cont',
            'MI_orange_chicken_cont',
          ],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_fc_comfort',
          label: 'Comfort food',
          emoji: '🧀',
          description: 'Cheesy loaded nachos, fries, cordon bleu & bites',
          active: true,
          sort_order: 5,
          signals: ['comfort', 'cheesy'],
          pinned_product_ids: [
            'MI_chicken_parmesan_main',
            'MI_chicken_cordon_bleu_cont',
            'MI_chips_and_queso_app',
            'MI_loaded_fries_app',
            'MI_loaded_nachos_app',
            'MI_pizza_bites_app',
          ],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_fc_meatfree',
          label: 'Meat-free favorites',
          emoji: '🌱',
          description: 'Crisp falafel, creamy hummus, samosas & paneer momo',
          active: true,
          sort_order: 6,
          signals: ['vegetarian'],
          pinned_product_ids: [
            'MI_falafel_app',
            'MI_hummus_app',
            'MI_veg_samosa_veg',
            'MI_paneer_momo_veg',
            'MI_daal_chawal_veg',
            'MI_spicy_aloo_chaat_app',
          ],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_fc_snack',
          label: 'Just a snack',
          emoji: '🍟',
          description: 'Pani puri, seasoned fries, kabob lollipops & papri chaat',
          active: true,
          sort_order: 7,
          signals: ['snack'],
          pinned_product_ids: [
            'MI_fries_app',
            'MI_dynamite_chicken_app',
            'MI_papri_chaat_app',
            'MI_pani_puri_app',
            'MI_kabob_lollipop_app',
            'MI_chips_and_queso_app',
          ],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_fc_surprise',
          label: 'Surprise me',
          emoji: '🎲',
          active: true,
          sort_order: 8,
          signals: ['variety'],
          pinned_product_ids: [
            'MI_chicken_dum_biryani_main',
            'MI_beef_smash_burger',
            'MI_dynamite_chicken_app',
            'MI_momo_cont',
          ],
          destination: { type: 'recommendations' },
        },
      ],
    },
    {
      id: 'q_food_hunger',
      stage: 'food',
      title: 'Hunger Level',
      question_text: 'How hungry are we talking? 😄',
      helper_text: 'Help us calibrate portions',
      emoji: '😄',
      type: 'single_select',
      active: true,
      sort_order: 2,
      required: false,
      skippable: true,
      repeat_policy: 'show_once',
      default_destination: { type: 'recommendations' },
      answers: [
        {
          id: 'ans_fh_snack',
          label: 'Just a little',
          emoji: '🥨',
          active: true,
          sort_order: 1,
          signals: ['snack'],
          pinned_product_ids: ['MI_hummus_app', 'MI_falafel_app', 'MI_fries_app'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_fh_full',
          label: 'Full meal',
          emoji: '🍽️',
          active: true,
          sort_order: 2,
          signals: ['main'],
          pinned_product_ids: ['MI_chicken_dum_biryani_main', 'MI_beef_smash_burger', 'MI_beef_koobideh_main'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_fh_share',
          label: 'Sharing with friends',
          emoji: '👯',
          active: true,
          sort_order: 3,
          signals: ['shareable'],
          pinned_product_ids: ['MI_loaded_nachos_app', 'MI_loaded_fries_app', 'MI_chips_and_queso_app'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_fh_variety',
          label: 'A little of everything',
          emoji: '🤔',
          active: true,
          sort_order: 4,
          signals: ['variety'],
          destination: { type: 'recommendations' },
        },
      ],
    },
    {
      id: 'q_food_flavor',
      stage: 'food',
      title: 'Flavor Mood',
      question_text: 'Pick your flavor mood 🌶️',
      helper_text: 'Spice level and flavor accent',
      emoji: '🌶️',
      type: 'single_select',
      active: true,
      sort_order: 3,
      required: false,
      skippable: true,
      repeat_policy: 'show_once',
      default_destination: { type: 'recommendations' },
      answers: [
        {
          id: 'ans_ff_spicy',
          label: 'Bring the heat',
          emoji: '🌶️',
          active: true,
          sort_order: 1,
          signals: ['spicy'],
          pinned_product_ids: ['MI_spicy_potato_app', 'MI_dynamite_chicken_app', 'MI_mirchi_paratha_roll', 'MI_wings_10pc'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_ff_savory',
          label: 'Savory & smoky',
          emoji: '🧄',
          active: true,
          sort_order: 2,
          signals: ['savory', 'grilled'],
          pinned_product_ids: ['MI_chicken_boti_main', 'MI_chicken_kabob_main', 'MI_beef_koobideh_main'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_ff_cheesy',
          label: 'Cheesy & creamy',
          emoji: '🧀',
          active: true,
          sort_order: 3,
          signals: ['cheesy', 'creamy'],
          pinned_product_ids: ['MI_chips_and_queso_app', 'MI_loaded_fries_app', 'MI_chicken_parmesan_main'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_ff_tangy',
          label: 'Fresh & tangy',
          emoji: '🍋',
          active: true,
          sort_order: 4,
          signals: ['tangy'],
          pinned_product_ids: ['MI_papri_chaat_app', 'MI_pani_puri_app', 'MI_shawarma_wrap'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_ff_sweet_savory',
          label: 'Sweet & savory',
          emoji: '🍯',
          active: true,
          sort_order: 5,
          signals: ['sweet_savory'],
          pinned_product_ids: ['MI_mongolian_chicken_cont', 'MI_orange_chicken_cont'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_ff_dealers',
          label: "Dealer's choice",
          emoji: '🎲',
          active: true,
          sort_order: 6,
          signals: ['variety'],
          destination: { type: 'recommendations' },
        },
      ],
    },

    /* ═══════════════ DESSERT STAGE (CART-CONDITIONAL) ═══════════════ */
    {
      id: 'q_dessert_prompt',
      stage: 'dessert',
      title: 'Sweet Ending',
      question_text: 'Should we save room for something sweet? 🍰',
      helper_text: 'Rich cheesecake, warm kunafa, or traditional desi desserts',
      emoji: '🍰',
      type: 'single_select',
      active: true,
      sort_order: 1,
      required: false,
      skippable: true,
      repeat_policy: 'cart_conditional',
      recommendation_config: {
        result_count: 3,
        eligible_category_ids: ['CAT_DESSERTS'],
      },
      answers: [
        {
          id: 'ans_d_traditional',
          label: 'Warm, rich & traditional',
          emoji: '🧀',
          description: 'Crispy warm Kunafa ($12) & Gulab Jamun ($8)',
          active: true,
          sort_order: 1,
          signals: ['traditional', 'warm'],
          pinned_product_ids: ['MI_kunafa_dessert', 'MI_gulab_jamun_dessert'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_d_cake',
          label: 'Cake lover',
          emoji: '🍰',
          description: 'Biscoff Cake ($12), Rasmalai Cake ($12) & Gajar Halwa Cheesecake ($14)',
          active: true,
          sort_order: 2,
          signals: ['cake'],
          pinned_product_ids: ['MI_biscoff_cake_dessert', 'MI_rasmalai_cake_dessert', 'MI_gajar_halwa_cheesecake_dessert'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_d_fruity',
          label: 'Fruity & creamy',
          emoji: '🥭',
          description: 'Mango Lassi Cheesecake ($14)',
          active: true,
          sort_order: 3,
          signals: ['fruity', 'creamy'],
          pinned_product_ids: ['MI_mango_lassi_cheesecake_dessert'],
          destination: { type: 'product', ref_id: 'MI_mango_lassi_cheesecake_dessert' },
        },
        {
          id: 'ans_d_pistachio',
          label: 'Chocolate or pistachio mood',
          emoji: '🍫',
          description: 'Kunafa with Pistachio or Nutella variation',
          active: true,
          sort_order: 4,
          signals: ['pistachio', 'chocolate'],
          pinned_product_ids: ['MI_kunafa_dessert'],
          destination: { type: 'product_customization', ref_id: 'MI_kunafa_dessert' },
        },
        {
          id: 'ans_d_surprise',
          label: 'Surprise me',
          emoji: '🎲',
          active: true,
          sort_order: 5,
          signals: ['variety'],
          pinned_product_ids: ['MI_kunafa_dessert', 'MI_biscoff_cake_dessert', 'MI_mango_lassi_cheesecake_dessert'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_d_no',
          label: 'Not right now',
          emoji: '🙅',
          active: true,
          sort_order: 6,
          signals: [],
          destination: { type: 'next_stage', ref_id: 'drinks' },
        },
      ],
    },

    /* ═══════════════ DRINKS STAGE ═══════════════ */
    {
      id: 'q_drink_type',
      stage: 'drinks',
      title: 'Beverage Vibe',
      question_text: 'What are we sipping tonight? 🥤',
      helper_text: 'Find your drink to pair with your hookah',
      emoji: '🥤',
      type: 'single_select',
      active: true,
      sort_order: 1,
      required: false,
      skippable: true,
      repeat_policy: 'show_once',
      default_destination: { type: 'recommendations' },
      recommendation_config: {
        result_count: 3,
      },
      answers: [
        {
          id: 'ans_b_minty',
          label: 'Refreshing & minty',
          emoji: '🍃',
          active: true,
          sort_order: 1,
          signals: ['minty', 'cold'],
          pinned_product_ids: ['MI_classic_mint_mojito', 'MI_mint_margarita', 'MI_mint_tea'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_b_tropical',
          label: 'Fruity & tropical',
          emoji: '🥭',
          active: true,
          sort_order: 2,
          signals: ['tropical', 'fruity'],
          pinned_product_ids: ['MI_mango_mojito', 'MI_lychee_mojito', 'MI_watermelon_juice', 'MI_orange_juice'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_b_creamy',
          label: 'Creamy & indulgent',
          emoji: '🧋',
          active: true,
          sort_order: 3,
          signals: ['creamy'],
          pinned_product_ids: ['MI_mango_shake', 'MI_sweet_lassi', 'MI_cold_coffee', 'MI_pistachio_latte'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_b_chai',
          label: 'Chai & coffee',
          emoji: '☕',
          active: true,
          sort_order: 4,
          signals: ['chai', 'coffee'],
          pinned_product_ids: ['MI_karak_chai', 'MI_kashmiri_chai', 'MI_desi_coffee', 'MI_pistachio_latte'],
          destination: { type: 'question', ref_id: 'q_drink_temp' },
        },
        {
          id: 'ans_b_soda',
          label: 'Classic soda ($4)',
          emoji: '🥤',
          description: 'Coke, Diet Coke, Sprite, Fanta, Ginger Ale, Dr Pepper',
          active: true,
          sort_order: 5,
          signals: ['soda'],
          pinned_product_ids: ['MI_soft_drinks_selection'],
          destination: { type: 'product_customization', ref_id: 'MI_soft_drinks_selection' },
        },
        {
          id: 'ans_b_energy',
          label: 'Keep me energized',
          emoji: '⚡',
          description: 'Red Bull ($6) Regular or Sugarfree',
          active: true,
          sort_order: 6,
          signals: ['energy'],
          pinned_product_ids: ['MI_red_bull'],
          destination: { type: 'product', ref_id: 'MI_red_bull' },
        },
        {
          id: 'ans_b_water',
          label: 'Keep it simple',
          emoji: '💧',
          description: 'Saratoga Natural Spring Water ($4.50) or Sparkling ($6)',
          active: true,
          sort_order: 7,
          signals: ['water'],
          pinned_product_ids: ['MI_saratoga_water', 'MI_sparkling_water'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_b_special',
          label: 'Something special',
          emoji: '🌈',
          description: "Ocean's Secret, Pina Colada & Red Affair signature mocktails",
          active: true,
          sort_order: 8,
          signals: ['special'],
          pinned_product_ids: ['MI_oceans_secret', 'MI_pina_colada', 'MI_red_affair', 'MI_rim_fire_melon'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_b_surprise',
          label: 'Surprise me',
          emoji: '🎲',
          active: true,
          sort_order: 9,
          signals: ['variety'],
          pinned_product_ids: ['MI_oceans_secret', 'MI_mango_mojito', 'MI_karak_chai'],
          destination: { type: 'recommendations' },
        },
      ],
    },
    {
      id: 'q_drink_temp',
      stage: 'drinks',
      title: 'Serving Temperature',
      question_text: 'Cold, hot, or somewhere in between? 🌡️',
      helper_text: 'Tell us how you want it served',
      emoji: '🌡️',
      type: 'single_select',
      active: true,
      sort_order: 2,
      required: false,
      skippable: true,
      repeat_policy: 'show_once',
      default_destination: { type: 'recommendations' },
      answers: [
        {
          id: 'ans_bt_cold',
          label: 'Ice cold',
          emoji: '🧊',
          active: true,
          sort_order: 1,
          signals: ['cold'],
          pinned_product_ids: ['MI_cold_coffee', 'MI_classic_mint_mojito', 'MI_mango_shake'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_bt_hot',
          label: 'Warm & cozy',
          emoji: '☕',
          active: true,
          sort_order: 2,
          signals: ['hot'],
          pinned_product_ids: ['MI_karak_chai', 'MI_kashmiri_chai', 'MI_desi_coffee', 'MI_moroccan_tea'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_bt_creamy',
          label: 'Creamy & chilled',
          emoji: '🥤',
          active: true,
          sort_order: 3,
          signals: ['creamy', 'cold'],
          pinned_product_ids: ['MI_mango_shake', 'MI_sweet_lassi', 'MI_cold_coffee'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_bt_any',
          label: 'Anything goes',
          emoji: '🤷',
          active: true,
          sort_order: 4,
          signals: ['variety'],
          destination: { type: 'recommendations' },
        },
      ],
    },
    {
      id: 'q_drink_flavor',
      stage: 'drinks',
      title: 'Drink Flavor',
      question_text: 'Which flavor sounds best? 🍋',
      helper_text: 'Pick a note for your mocktail or refresher',
      emoji: '🍋',
      type: 'single_select',
      active: true,
      sort_order: 3,
      required: false,
      skippable: true,
      repeat_policy: 'show_once',
      default_destination: { type: 'recommendations' },
      answers: [
        {
          id: 'ans_bf_citrus',
          label: 'Citrus & tangy',
          emoji: '🍋',
          active: true,
          sort_order: 1,
          signals: ['citrus', 'tangy'],
          pinned_product_ids: ['MI_classic_mint_mojito', 'MI_mint_margarita', 'MI_orange_juice'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_bf_tropical',
          label: 'Mango & tropical',
          emoji: '🥭',
          active: true,
          sort_order: 2,
          signals: ['tropical'],
          pinned_product_ids: ['MI_mango_mojito', 'MI_mango_shake', 'MI_pina_colada'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_bf_melon',
          label: 'Melon & juicy',
          emoji: '🍉',
          active: true,
          sort_order: 3,
          signals: ['melon'],
          pinned_product_ids: ['MI_rim_fire_melon', 'MI_watermelon_juice'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_bf_floral',
          label: 'Floral & exotic',
          emoji: '🌺',
          active: true,
          sort_order: 4,
          signals: ['floral', 'exotic'],
          pinned_product_ids: ['MI_lychee_mojito', 'MI_red_affair', 'MI_oceans_secret'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_bf_creamy',
          label: 'Smooth & creamy',
          emoji: '🥛',
          active: true,
          sort_order: 5,
          signals: ['creamy'],
          pinned_product_ids: ['MI_sweet_lassi', 'MI_mango_shake', 'MI_cold_coffee'],
          destination: { type: 'recommendations' },
        },
        {
          id: 'ans_bf_surprise',
          label: 'Surprise me',
          emoji: '🎲',
          active: true,
          sort_order: 6,
          signals: ['variety'],
          destination: { type: 'recommendations' },
        },
      ],
    },

    /* ═══════════════ FINAL OPTIONAL NUDGE ═══════════════ */
    {
      id: 'q_checkout_nudge',
      stage: 'checkout',
      title: 'Review Nudge',
      question_text: 'Have we got your whole vibe? ',
      helper_text: 'Ready to order or want to add one last item?',
      emoji: '',
      type: 'single_select',
      active: true,
      sort_order: 1,
      required: false,
      skippable: true,
      repeat_policy: 'show_once',
      answers: [
        {
          id: 'ans_c_ready',
          label: "I'm ready to checkout",
          emoji: '🛍️',
          active: true,
          sort_order: 1,
          signals: [],
          destination: { type: 'end_discovery' },
        },
        {
          id: 'ans_c_food',
          label: 'One more bite',
          emoji: '🍟',
          active: true,
          sort_order: 2,
          signals: [],
          destination: { type: 'next_stage', ref_id: 'food' },
        },
        {
          id: 'ans_c_drink',
          label: 'One more sip',
          emoji: '🥤',
          active: true,
          sort_order: 3,
          signals: [],
          destination: { type: 'next_stage', ref_id: 'drinks' },
        },
        {
          id: 'ans_c_hookah',
          label: 'More hookah options',
          emoji: '💨',
          active: true,
          sort_order: 4,
          signals: [],
          destination: { type: 'next_stage', ref_id: 'hookah' },
        },
      ],
    },
  ];
}

export function buildCavalliVerifiedTags(): Record<string, string[]> {
  return {
    MI_spicy_potato_app: ['spicy'],
    MI_spicy_aloo_chaat_app: ['spicy'],
    MI_dynamite_chicken_app: ['spicy'],
    MI_dynamite_chicken_wrap: ['spicy'],
    MI_mirchi_paratha_roll: ['spicy'],
    MI_chili_chicken_cont: ['spicy'],
    MI_kung_pao_chicken_cont: ['spicy', 'contains_peanuts'],
    MI_chicken_boti_main: ['grilled', 'savory'],
    MI_chicken_kabob_main: ['grilled', 'savory'],
    MI_lamb_chops_main: ['grilled'],
    MI_beef_koobideh_main: ['grilled', 'savory'],
    ITM_9CD79FD00822: ['grilled', 'savory'], // Sizzling Gola Kabob
    ITM_C651EACD4115: ['grilled', 'creamy'], // Malai Chicken Boti
    MI_chips_and_queso_app: ['cheesy', 'shareable'],
    MI_loaded_fries_app: ['cheesy', 'shareable'],
    MI_loaded_nachos_app: ['cheesy', 'shareable'],
    MI_pizza_bites_app: ['cheesy', 'snack'],
    MI_chicken_parmesan_main: ['cheesy'],
    MI_chicken_cordon_bleu_cont: ['cheesy'],
    MI_hummus_app: ['shareable', 'snack', 'vegetarian'],
    MI_falafel_app: ['vegetarian', 'snack'],
    MI_veg_samosa_veg: ['vegetarian', 'snack'],
    MI_daal_chawal_veg: ['vegetarian'],
    MI_paneer_momo_veg: ['vegetarian'],
    MI_fries_app: ['snack', 'vegetarian'],
    MI_pani_puri_app: ['snack', 'vegetarian', 'tangy'],
    MI_papri_chaat_app: ['snack', 'vegetarian', 'tangy'],
    MI_kabob_lollipop_app: ['snack', 'shareable'],
    MI_shawarma_wrap: ['tangy'],
    MI_shawarma_plate_main: ['savory'],
    MI_beef_smash_burger: ['main'],
    MI_chicken_zinger_burger: ['main'],
    MI_momo_cont: ['shareable', 'snack'],
    MI_chow_mein_cont: ['main'],
    MI_mongolian_chicken_cont: ['sweet_savory'],
    MI_orange_chicken_cont: ['sweet_savory'],
    MI_wings_10pc: ['shareable', 'spicy'],
    MI_wings_6pc: ['snack'],
    MI_kunafa_dessert: ['traditional', 'warm', 'pistachio'],
    MI_gulab_jamun_dessert: ['traditional', 'warm'],
    MI_biscoff_cake_dessert: ['cake', 'creamy'],
    MI_rasmalai_cake_dessert: ['cake', 'traditional'],
    MI_gajar_halwa_cheesecake_dessert: ['cake', 'traditional', 'creamy'],
    MI_mango_lassi_cheesecake_dessert: ['cake', 'creamy', 'fruity'],
    MI_classic_mint_mojito: ['minty', 'cold', 'citrus'],
    MI_mint_margarita: ['minty', 'cold', 'citrus'],
    MI_mint_tea: ['minty', 'hot'],
    MI_mango_mojito: ['tropical', 'cold', 'fruity'],
    MI_lychee_mojito: ['floral', 'cold', 'fruity'],
    MI_watermelon_juice: ['fruity', 'cold', 'melon'],
    MI_orange_juice: ['citrus', 'cold', 'fruity'],
    MI_mango_shake: ['creamy', 'tropical', 'cold'],
    MI_sweet_lassi: ['creamy', 'cold'],
    MI_cold_coffee: ['creamy', 'cold', 'coffee'],
    MI_karak_chai: ['chai', 'hot'],
    MI_kashmiri_chai: ['chai', 'hot', 'creamy'],
    MI_desi_coffee: ['coffee', 'hot'],
    MI_moroccan_tea: ['hot'],
    MI_pistachio_latte: ['coffee', 'hot', 'creamy'],
    MI_soft_drinks_selection: ['soda', 'cold'],
    MI_red_bull: ['energy', 'cold'],
    MI_saratoga_water: ['water', 'cold'],
    MI_sparkling_water: ['water', 'cold'],
    MI_oceans_secret: ['special', 'cold', 'tropical'],
    MI_pina_colada: ['special', 'cold', 'tropical', 'creamy'],
    MI_red_affair: ['special', 'cold', 'floral'],
    MI_rim_fire_melon: ['special', 'cold', 'melon'],
  };
}

async function run() {
  const shouldPublish = process.argv.includes('--publish');
  console.log(`🚀 Starting Cavalli Vibe Quest Seeding (tenant=${RID}, publish=${shouldPublish})...`);

  const client = new MongoClient(uri);
  await client.connect();
  const db = client.db('benzin_saas_db');

  const rest = await db.collection<any>('restaurants').findOne({ _id: RID });
  if (!rest) {
    console.error(`❌ Restaurant ${RID} not found in database!`);
    await client.close();
    process.exit(1);
  }

  const catalogCategories = await db.collection('menu_categories').find({ restaurant_id: RID }).toArray();
  const catalogProducts = await db.collection('menu_items').find({ restaurant_id: RID }).toArray();

  console.log(`✅ Loaded catalog: ${catalogCategories.length} categories, ${catalogProducts.length} items`);

  const questions = buildCavalliVibeQuestQuestions();
  const productTags = buildCavalliVerifiedTags();

  const draftConfig: VibeQuestConfig = {
    version: 1,
    enabled: true,
    questions,
    settings: {
      dessert_category_ids: ['CAT_DESSERTS'],
      dessert_trigger_stage: 'dessert',
      intro_title: 'Welcome to Cavalli Huqqa ',
      intro_subtitle: "Let's find your vibe. Tell us what sounds good, discover a few favorites, and skip anytime.",
      reactions: {
        fruity: "Sweet and fruity? We've got a vibe for that 🍓",
        spicy: "Something spicy? Say less 🌶️",
        traditional: "A sweet ending sounds tempting 🍰",
        tropical: "Let's find your perfect sip 🥭",
        variety: "Not sure? We'll surprise you ",
      },
    },
    product_tags: productTags,
    updated_at: new Date().toISOString(),
  };

  console.log(`🔍 Validating draft config against live catalog...`);
  const validation = VibeQuestEngine.validateConfig(draftConfig, catalogCategories, catalogProducts);

  console.log(`Validation result: ${validation.valid ? 'VALID ✅' : 'INVALID ❌'}`);
  if (validation.errors.length > 0) {
    console.log(`Errors/Warnings (${validation.errors.length}):`);
    validation.errors.forEach((e) => {
      console.log(`  [${e.severity.toUpperCase()}] ${e.question_id ? e.question_id + ': ' : ''}${e.message}`);
    });
  }

  if (!validation.valid) {
    console.error('❌ Draft validation failed with critical errors. Aborting seed.');
    await client.close();
    process.exit(1);
  }

  const now = new Date().toISOString();
  const updatePayload: any = {
    'settings.vibe_quest.draft': draftConfig,
    'settings.vibe_quest.updated_at': now,
  };

  if (shouldPublish) {
    draftConfig.published_at = now;
    updatePayload['settings.vibe_quest.enabled'] = true;
    updatePayload['settings.vibe_quest.published_version'] = 1;
    updatePayload['settings.vibe_quest.published'] = draftConfig;
    updatePayload['settings.vibe_quest.published_at'] = now;
  }

  await db.collection<any>('restaurants').updateOne(
    { _id: RID },
    { $set: updatePayload }
  );

  console.log(`🎉 Successfully seeded Cavalli Vibe Quest ${shouldPublish ? 'and PUBLISHED' : 'as DRAFT'}!`);
  await client.close();
}

if (require.main === module) {
  run().catch((err) => {
    console.error('Fatal error during seed:', err);
    process.exit(1);
  });
}
