import fs from 'fs';
import path from 'path';
import { MultiTenantDbService } from '../services/multi-tenant-db.service';
import { MenuCategory, MenuItemModel, ModifierGroup } from '../models/types';

const DB_FILE = path.join(__dirname, '../../multi_tenant_db.json');

async function seedVinduMenu() {
  console.log('🍛 Seeding Vindu Indian Cuisine Menu from vindudallas.com...');

  // Initialize DB Service
  await MultiTenantDbService.initialize();

  const rawData = fs.readFileSync(DB_FILE, 'utf8');
  const db = JSON.parse(rawData);

  const VINDU_RES_ID = 'RES_3B53E12445A4';

  // 1. Update or Create Restaurant Entry
  let vindu = db.restaurants.find((r: any) => r._id === VINDU_RES_ID || r.slug === 'vindu');
  if (!vindu) {
    vindu = {
      _id: VINDU_RES_ID,
      name: 'Vindu Indian Cuisine',
      slug: 'vindu',
      restaurant_code: '5270',
      branding: {
        primary_color: '#E58A1F',    // Saffron Gold
        secondary_color: '#B91C1C',  // Clay Oven Red
        accent_color: '#15803D',     // Emerald Cardamom
        background_color: '#0D0A08', // Deep Charcoal
        card_color: '#1A1410',       // Warm Card
        text_color: '#FFF8F0',       // Cream
        muted_color: '#A39284',
        logo_url: null,
        font_family: 'ui-rounded',
      },
      settings: {
        currency: 'USD',
        timezone: 'America/Chicago',
        address: '4701 Frankford Rd, Ste 237, Dallas, TX 75287',
        phone: '(972) 931-5999',
        tax_config: { default_rate: 0.0825, category_rates: {} },
        auto_accept_orders: false,
        require_table_number: true,
        enable_tips: true,
        tip_options: [15, 18, 20, 25],
        enable_split_payment: true,
        session_timeout_minutes: 5,
        payment_provider: 'square',
        payment_credentials: {},
      },
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };
    db.restaurants.push(vindu);
  } else {
    vindu.name = 'Vindu Indian Cuisine';
    vindu.slug = 'vindu';
    vindu.restaurant_code = '5270';
    vindu.branding = {
      primary_color: '#E58A1F',
      secondary_color: '#B91C1C',
      accent_color: '#15803D',
      background_color: '#0D0A08',
      card_color: '#1A1410',
      text_color: '#FFF8F0',
      muted_color: '#A39284',
      logo_url: null,
      font_family: 'ui-rounded',
    };
    vindu.settings = {
      ...vindu.settings,
      address: '4701 Frankford Rd, Ste 237, Dallas, TX 75287',
      phone: '(972) 931-5999',
    };
    vindu.updated_at = new Date().toISOString();
  }

  // 2. Define Standard Modifier Groups
  const spiceLevelMod: ModifierGroup = {
    id: 'MOD_SPICE_LEVEL',
    name: 'Spice Level',
    required: false,
    max_selections: 1,
    options: [
      { id: 'SPICE_MILD', name: 'Mild', price_adjustment: 0 },
      { id: 'SPICE_MED', name: 'Medium (Default)', price_adjustment: 0 },
      { id: 'SPICE_HOT', name: 'Spicy / Hot 🔥', price_adjustment: 0 },
      { id: 'SPICE_EXTRA', name: 'Desi Extra Spicy 🔥🔥', price_adjustment: 0 },
    ],
  };

  const biryaniSidesMod: ModifierGroup = {
    id: 'MOD_BIRYANI_SIDES',
    name: 'Biryani Accompaniments',
    required: false,
    max_selections: 2,
    options: [
      { id: 'SIDE_RAITHA', name: 'Extra Cucumber Raitha', price_adjustment: 1.99 },
      { id: 'SIDE_SALAN', name: 'Extra Mirchi Ka Salan Gravy', price_adjustment: 2.49 },
      { id: 'SIDE_BOILED_EGG', name: 'Extra Boiled Egg', price_adjustment: 1.50 },
    ],
  };

  const dosaAccompanimentMod: ModifierGroup = {
    id: 'MOD_DOSA_ACCOMP',
    name: 'Dosa Accompaniments',
    required: false,
    max_selections: 2,
    options: [
      { id: 'DOSA_EXTRA_SAMBAR', name: 'Extra Lentil Sambar (8oz)', price_adjustment: 2.49 },
      { id: 'DOSA_EXTRA_CHUTNEY', name: 'Extra Coconut & Tomato Chutney', price_adjustment: 1.99 },
      { id: 'DOSA_GHEE_ROAST', name: 'Ghee Roast Finish', price_adjustment: 1.50 },
    ],
  };

  const naanButterMod: ModifierGroup = {
    id: 'MOD_BREAD_FINISH',
    name: 'Bread Finish',
    required: false,
    max_selections: 1,
    options: [
      { id: 'BREAD_BUTTER', name: 'Brushed with Pure Butter (Default)', price_adjustment: 0 },
      { id: 'BREAD_DRY', name: 'No Butter (Dry / Vegan)', price_adjustment: 0 },
      { id: 'BREAD_EXTRA_GARLIC', name: 'Extra Roasted Garlic & Cilantro', price_adjustment: 0.99 },
    ],
  };

  // 3. Define 12 Menu Categories
  const categories: MenuCategory[] = [
    {
      _id: 'CAT_VINDU_VEG_APP',
      restaurant_id: VINDU_RES_ID,
      title: 'Vegetarian Starters',
      subtitle: 'Crispy Fritters, Pakoras & Indo-Chinese',
      icon: '🥟',
      color: '#15803D',
      sort_order: 1,
      menu_type: 'food',
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'CAT_VINDU_NONVEG_APP',
      restaurant_id: VINDU_RES_ID,
      title: 'Non-Vegetarian Starters',
      subtitle: 'Chicken 65, Chilly Chicken & Meat Samosas',
      icon: '🍗',
      color: '#B91C1C',
      sort_order: 2,
      menu_type: 'food',
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'CAT_VINDU_DOSAS',
      restaurant_id: VINDU_RES_ID,
      title: 'South Indian Tiffins & Dosas',
      subtitle: 'Crispy Crepes, Idli & Medhu Vada with Sambar',
      icon: '🥞',
      color: '#E58A1F',
      sort_order: 3,
      menu_type: 'food',
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'CAT_VINDU_TANDOORI',
      restaurant_id: VINDU_RES_ID,
      title: 'Tandoori Sizzlers & Kebabs',
      subtitle: 'Clay Oven Roasted Chicken, Lamb & Paneer',
      icon: '🍢',
      color: '#DC2626',
      sort_order: 4,
      menu_type: 'food',
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'CAT_VINDU_CHICKEN',
      restaurant_id: VINDU_RES_ID,
      title: 'Chicken Entrées & Curries',
      subtitle: 'Tikka Masala, Butter Chicken & Chettinad',
      icon: '🥘',
      color: '#EA580C',
      sort_order: 5,
      menu_type: 'food',
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'CAT_VINDU_LAMB_GOAT',
      restaurant_id: VINDU_RES_ID,
      title: 'Lamb & Goat Specialties',
      subtitle: 'Rogan Josh, Hyderabadi Goat Curry & Korma',
      icon: '🥩',
      color: '#7F1D1D',
      sort_order: 6,
      menu_type: 'food',
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'CAT_VINDU_SEAFOOD',
      restaurant_id: VINDU_RES_ID,
      title: 'Seafood Specialties',
      subtitle: 'Nellore Fish Curry & Shrimp Masala',
      icon: '🍤',
      color: '#0284C7',
      sort_order: 7,
      menu_type: 'food',
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'CAT_VINDU_VEG_ENTREE',
      restaurant_id: VINDU_RES_ID,
      title: 'Vegetarian Entrées',
      subtitle: 'Paneer Butter Masala, Palak & Daal Makhani',
      icon: '🧀',
      color: '#16A34A',
      sort_order: 8,
      menu_type: 'food',
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'CAT_VINDU_BIRYANI',
      restaurant_id: VINDU_RES_ID,
      title: 'Royal Dum Biryanis & Rice',
      subtitle: 'Slow-cooked Basmati Rice with Saffron & Spices',
      icon: '🍚',
      color: '#D97706',
      sort_order: 9,
      menu_type: 'food',
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'CAT_VINDU_BREADS',
      restaurant_id: VINDU_RES_ID,
      title: 'Fresh Tandoori Breads',
      subtitle: 'Garlic Naan, Roti, Onion Kulcha & Parathas',
      icon: '🫓',
      color: '#CA8A04',
      sort_order: 10,
      menu_type: 'food',
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'CAT_VINDU_INDOCHINESE',
      restaurant_id: VINDU_RES_ID,
      title: 'Indo-Chinese Specials',
      subtitle: 'Fried Rice, Hakka Noodles & Manchurian',
      icon: '🥢',
      color: '#9333EA',
      sort_order: 11,
      menu_type: 'food',
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'CAT_VINDU_DESSERTS_BEV',
      restaurant_id: VINDU_RES_ID,
      title: 'Desserts & Beverages',
      subtitle: 'Mango Lassi, Masala Chai, Gulab Jamun & Kulfi',
      icon: '🍨',
      color: '#E11D48',
      sort_order: 12,
      menu_type: 'drinks',
      active: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];

  // 4. Define All Menu Items
  const items: MenuItemModel[] = [
    // 🥟 Vegetarian Starters
    {
      _id: 'MI_VINDU_VEG_SAMOSA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_APP',
      name: 'Vegetable Samosa (2 pcs)',
      price: 7.99,
      desc: 'Golden crispy pastry turnovers filled with seasoned potatoes, green peas, and fragrant herbs. Served with mint and tamarind chutneys.',
      emoji: '🥟',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_ONION_PAKORA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_APP',
      name: 'Onion Pakora',
      price: 9.99,
      desc: 'Crispy julienned onions dipped in a spiced chickpea flour batter with curry leaves and deep-fried till golden.',
      emoji: '🧅',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_SPINACH_PAKORA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_APP',
      name: 'Spinach Pakora (Palak)',
      price: 9.99,
      desc: 'Fresh baby spinach leaves lightly battered in seasoned gram flour and flash-fried crisp.',
      emoji: '🥬',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CUT_MIRCHI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_APP',
      name: 'Cut Mirchi',
      price: 8.99,
      desc: 'South Indian style battered long green chilies, deep-fried, sliced into bite-size pieces, and double-fried with chaat masala.',
      emoji: '🌶️',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 4,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_GOBI_MANCHURIAN',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_APP',
      name: 'Gobi Manchurian (Dry / Gravy)',
      price: 12.99,
      desc: 'Crispy cauliflower florets wok-tossed in tangy Indo-Chinese garlic, ginger, and soy sauce glaze with green scallions.',
      emoji: '🥦',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 5,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CHILLY_PANEER',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_APP',
      name: 'Chilly Paneer',
      price: 13.99,
      desc: 'Tender cottage cheese cubes tossed with crisp bell peppers, onions, fresh green chilies, and savory oriental chili sauce.',
      emoji: '🧀',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_PANEER_65',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_APP',
      name: 'Paneer 65',
      price: 13.99,
      desc: 'Fresh paneer cubes tossed in a fiery South Indian yogurt-based masala tempered with curry leaves and mustard seeds.',
      emoji: '🧀',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 7,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },

    // 🍗 Non-Vegetarian Starters
    {
      _id: 'MI_VINDU_CHICKEN_65',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_NONVEG_APP',
      name: 'Chicken 65',
      price: 14.99,
      desc: 'Signature South Indian spicy marinated boneless chicken bites fried crisp and tempered with curry leaves, crushed pepper, and green chilies.',
      emoji: '🍗',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CHILLY_CHICKEN',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_NONVEG_APP',
      name: 'Chilly Chicken',
      price: 14.99,
      desc: 'Crisp boneless chicken tossed with sweet bell peppers, red onions, garlic, and hot chili-soy sauce.',
      emoji: '🌶️',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CHICKEN_LAL_MIRCHI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_NONVEG_APP',
      name: 'Chicken Lal Mirchi',
      price: 14.99,
      desc: 'Spicy chicken morsels sauteed with coarsely crushed Guntur red chilies, curry leaves, and black peppercorns.',
      emoji: '🔥',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_MEAT_SAMOSA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_NONVEG_APP',
      name: 'Meat Samosa (2 pcs)',
      price: 8.99,
      desc: 'Flaky pastry turnovers stuffed with spiced minced lamb, sweet peas, and ground garam masala.',
      emoji: '🥟',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 4,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_MEAT_PLATTER',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_NONVEG_APP',
      name: 'Vindu Meat Sampler Platter',
      price: 17.99,
      desc: 'Deluxe combination of Chicken Tikka, Seekh Kabab, Chicken 65, and Meat Samosa served with lemon wedges and mint dip.',
      emoji: '🍢',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 5,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },

    // 🥞 South Indian Tiffins & Dosas
    {
      _id: 'MI_VINDU_PLAIN_DOSA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DOSAS',
      name: 'Classic Plain Dosa',
      price: 9.99,
      desc: 'Golden crispy fermented rice and black lentil crepe served with flavorful vegetable sambar and fresh coconut chutneys.',
      emoji: '🥞',
      image_url: null,
      available: true,
      modifier_groups: [dosaAccompanimentMod],
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_MASALA_DOSA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DOSAS',
      name: 'Traditional Masala Dosa',
      price: 11.99,
      desc: 'Crispy golden crepe stuffed with a savory spiced potato and onion mash with mustard seed tempering.',
      emoji: '🥔',
      image_url: null,
      available: true,
      modifier_groups: [dosaAccompanimentMod],
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_MYSORE_MASALA_DOSA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DOSAS',
      name: 'Mysore Masala Dosa',
      price: 11.99,
      desc: 'Crispy crepe coated with spicy red chili-garlic paste and filled with rich spiced potato masala.',
      emoji: '🌶️',
      image_url: null,
      available: true,
      modifier_groups: [dosaAccompanimentMod],
      sort_order: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_ONION_RAVA_DOSA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DOSAS',
      name: 'Onion Rava Masala Dosa',
      price: 12.99,
      desc: 'Lacy semolina and rice crepe studded with diced onions, crushed cumin, and ginger, filled with potato masala.',
      emoji: '🧅',
      image_url: null,
      available: true,
      modifier_groups: [dosaAccompanimentMod],
      sort_order: 4,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_PANEER_DOSA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DOSAS',
      name: 'Shredded Paneer Dosa',
      price: 13.99,
      desc: 'Crisp crepe filled with spiced shredded Indian cottage cheese, onions, and fresh cilantro.',
      emoji: '🧀',
      image_url: null,
      available: true,
      modifier_groups: [dosaAccompanimentMod],
      sort_order: 5,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_IDLI_SAMBAR',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DOSAS',
      name: 'Steamed Idli with Sambar (3 pcs)',
      price: 9.99,
      desc: 'Pillow-soft steamed rice cakes served submerged in piping hot spiced lentil soup with coconut and tomato chutneys.',
      emoji: '⚪',
      image_url: null,
      available: true,
      modifier_groups: [dosaAccompanimentMod],
      sort_order: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_MEDHU_VADA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DOSAS',
      name: 'Medhu Vada (3 pcs)',
      price: 9.99,
      desc: 'Crispy golden savory lentil donuts seasoned with crushed black pepper and ginger, served with fresh sambar.',
      emoji: '🍩',
      image_url: null,
      available: true,
      modifier_groups: [dosaAccompanimentMod],
      sort_order: 7,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_ONION_CHILI_UTTAPPAM',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DOSAS',
      name: 'Onion & Chili Uttappam',
      price: 11.99,
      desc: 'Thick savory lentil-rice pancake griddled with sweet red onions, chopped tomatoes, and green chilies.',
      emoji: '🥞',
      image_url: null,
      available: true,
      modifier_groups: [dosaAccompanimentMod],
      sort_order: 8,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },

    // 🍢 Tandoori Sizzlers & Kebabs
    {
      _id: 'MI_VINDU_TANDOORI_CHICKEN',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_TANDOORI',
      name: 'Tandoori Chicken (Half / Full)',
      price: 14.99,
      desc: 'Fresh bone-in chicken marinated in hung yogurt, Kashmiri paprika, ginger, and roasted garam masala, grilled over charcoal.',
      emoji: '🍗',
      image_url: null,
      available: true,
      modifier_groups: [
        {
          id: 'MOD_TANDOORI_SIZE',
          name: 'Portion Size',
          required: false,
          max_selections: 1,
          options: [
            { id: 'SIZE_HALF', name: 'Half Chicken (Default)', price_adjustment: 0 },
            { id: 'SIZE_FULL', name: 'Full Chicken', price_adjustment: 8.00 },
          ],
        },
        spiceLevelMod,
      ],
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CHICKEN_TIKKA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_TANDOORI',
      name: 'Chicken Tikka Kebab',
      price: 15.99,
      desc: 'Succulent boneless chicken breast cubes marinated in sour cream, lemon, and tandoori herbs, charred on skewers.',
      emoji: '🍢',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_LAMB_SEEKH_KEBAB',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_TANDOORI',
      name: 'Lamb Seekh Kebab',
      price: 16.99,
      desc: 'Finely ground minced lamb blended with mint, onions, toasted coriander seeds, and roasted over open fire.',
      emoji: '🍢',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_PANEER_TIKKA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_TANDOORI',
      name: 'Paneer Tikka Sizzler',
      price: 14.99,
      desc: 'Thick slabs of cottage cheese, sweet bell peppers, and onions skewered and roasted in the clay tandoor.',
      emoji: '🧀',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 4,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_TANDOORI_LAMB_CHOPS',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_TANDOORI',
      name: 'Tandoori Lamb Chops',
      price: 21.99,
      desc: 'Premium tender lamb chops steeped in papaya marinade, green cardamom, and nutmeg, grilled over glowing charcoal.',
      emoji: '🥩',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 5,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_TANDOORI_SHRIMP',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_TANDOORI',
      name: 'Tandoori Jumbo Shrimp',
      price: 18.99,
      desc: 'Jumbo tiger shrimp marinated in carom seeds (ajwain), mustard oil, yogurt, and roasted to juicy perfection.',
      emoji: '🍤',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },

    // 🥘 Chicken Entrées & Curries
    {
      _id: 'MI_VINDU_CHICKEN_TIKKA_MASALA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_CHICKEN',
      name: 'Chicken Tikka Masala',
      price: 16.99,
      desc: 'America’s favorite curry: Fire-roasted chicken tikka simmered in a luscious, velvety tomato-cream sauce with fenugreek leaves.',
      emoji: '🥘',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_BUTTER_CHICKEN',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_CHICKEN',
      name: 'Chicken Makhani (Butter Chicken)',
      price: 15.99,
      desc: 'Tandoori-roasted pulled chicken steeped in a buttery, silky tomato gravy seasoned with aromatic cardamom and honey.',
      emoji: '🍛',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CHICKEN_CHETTINAD',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_CHICKEN',
      name: 'Chicken Chettinad',
      price: 15.99,
      desc: 'Bold and fiery South Indian coastal curry crafted with roasted coconut, black pepper, fennel, and curry leaves.',
      emoji: '🌶️',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CHICKEN_KORMA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_CHICKEN',
      name: 'Chicken Shahi Korma',
      price: 15.99,
      desc: 'Delicate Mughlai specialty: Boneless chicken slow-braised in an ultra-creamy cashew nut, almond, and saffron sauce.',
      emoji: '🍲',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 4,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CHICKEN_SAAG',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_CHICKEN',
      name: 'Chicken Saag (Palak)',
      price: 15.99,
      desc: 'Tender chicken pieces cooked gently in a wholesome puree of fresh spinach, garlic, ginger, and ground spices.',
      emoji: '🥬',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 5,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CHICKEN_VINDALOO',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_CHICKEN',
      name: 'Chicken Vindaloo',
      price: 15.99,
      desc: 'Fiery Goan specialty: Chicken and Yukon potatoes cooked in a tangy red wine vinegar, roasted chili, and garlic gravy.',
      emoji: '🔥',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_KADAI_CHICKEN',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_CHICKEN',
      name: 'Kadai Chicken',
      price: 15.99,
      desc: 'Chicken wok-cooked with thick chunks of bell peppers, sweet red onions, and freshly roasted coriander and cumin seeds.',
      emoji: '🍳',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 7,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },

    // 🥩 Lamb & Goat Specialties
    {
      _id: 'MI_VINDU_LAMB_ROGAN_JOSH',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_LAMB_GOAT',
      name: 'Kashmiri Lamb Rogan Josh',
      price: 17.99,
      desc: 'Tender morsels of Australian lamb slow-simmered in an authentic gravy of Kashmiri chilies, mace, fennel, and whole spices.',
      emoji: '🥩',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_LAMB_TIKKA_MASALA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_LAMB_GOAT',
      name: 'Lamb Tikka Masala',
      price: 17.99,
      desc: 'Tender boneless lamb pieces finished in our rich, spiced creamy tomato and onion masala sauce.',
      emoji: '🥘',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_LAMB_VINDALOO',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_LAMB_GOAT',
      name: 'Lamb Vindaloo',
      price: 17.99,
      desc: 'Succulent lamb cubes and potatoes simmered in an extra-spicy Goan red chili and vinegar reduction.',
      emoji: '🔥',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_HYD_GOAT_CURRY',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_LAMB_GOAT',
      name: 'Hyderabadi Goat Curry (Bone-In)',
      price: 16.99,
      desc: 'Traditional homestyle tender young baby goat stewed on slow fire with caramelised onions, tomatoes, and aromatic whole spices.',
      emoji: '🐐',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 4,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_GOAT_SUKKA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_LAMB_GOAT',
      name: 'Goat Sukka Fry',
      price: 17.99,
      desc: 'Semi-dry pan-roasted goat tossed with freshly crushed black peppercorns, curry leaves, and roasted coconut flakes.',
      emoji: '🍳',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 5,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },

    // 🍤 Seafood Specialties
    {
      _id: 'MI_VINDU_NELLORE_FISH_CURRY',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_SEAFOOD',
      name: 'Nellore Chepala Pulusu (Fish Curry)',
      price: 17.99,
      desc: 'South Indian coastal specialty: Tilapia fillets simmered in a tangy tamarind, tomato, and fenugreek seed curry.',
      emoji: '🐟',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_SHRIMP_TIKKA_MASALA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_SEAFOOD',
      name: 'Shrimp Tikka Masala',
      price: 18.99,
      desc: 'Plump tiger shrimp simmered in a rich tomato, butter, and sweet fenugreek cream sauce.',
      emoji: '🍤',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_SHRIMP_VINDALOO',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_SEAFOOD',
      name: 'Shrimp Vindaloo',
      price: 18.99,
      desc: 'Juicy shrimp and potatoes tossed in a fiery, sour Goan chili and garlic sauce.',
      emoji: '🔥',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },

    // 🧀 Vegetarian Entrées
    {
      _id: 'MI_VINDU_PANEER_BUTTER_MASALA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_ENTREE',
      name: 'Paneer Butter Masala',
      price: 14.99,
      desc: 'Fresh homemade cottage cheese cubes simmered in a rich, buttery tomato-cream sauce with fragrant dried fenugreek.',
      emoji: '🧀',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_PALAK_PANEER',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_ENTREE',
      name: 'Palak Paneer (Saag)',
      price: 14.99,
      desc: 'Tender paneer cubes cooked in a vibrant, spiced fresh baby spinach gravy enriched with garlic and butter.',
      emoji: '🥬',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_BAGARA_BAINGAN',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_ENTREE',
      name: 'Hyderabadi Bagara Baingan',
      price: 13.99,
      desc: 'Classic Royal Hyderabadi delicacy: Baby eggplants cooked in a rich, roasted sesame, peanut, coconut, and tamarind gravy.',
      emoji: '🍆',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_DAAL_MAKHANI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_ENTREE',
      name: 'Dal Makhani',
      price: 13.99,
      desc: 'Whole black lentils and red kidney beans slow-cooked overnight over embers with churned butter and fresh cream.',
      emoji: '🫘',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 4,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_YELLOW_DAAL_TADKA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_ENTREE',
      name: 'Yellow Dal Tadka',
      price: 12.99,
      desc: 'Creamy yellow toor lentils tempered with desi ghee, cumin seeds, browned garlic, and dried red chilies.',
      emoji: '🥣',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 5,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CHANA_MASALA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_ENTREE',
      name: 'Amritsari Chana Masala',
      price: 13.99,
      desc: 'Tender garbanzo chickpeas simmered in a spiced onion, tomato, and dried pomegranate seed gravy.',
      emoji: '🧆',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_MALAI_KOFTA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_ENTREE',
      name: 'Malai Kofta',
      price: 14.99,
      desc: 'Melt-in-mouth cottage cheese and potato dumplings stuffed with nuts and raisins, served in a rich cashew cream sauce.',
      emoji: '🥟',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 7,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_ALOO_GOBI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_VEG_ENTREE',
      name: 'Aloo Gobi Masala',
      price: 13.99,
      desc: 'Fresh cauliflower florets and tender potatoes stir-fried with turmeric, ginger, tomatoes, and ground cumin.',
      emoji: '🥔',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 8,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },

    // 🍚 Royal Dum Biryanis & Rice
    {
      _id: 'MI_VINDU_HYD_CHICKEN_BIRYANI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_BIRYANI',
      name: 'Hyderabadi Chicken Dum Biryani',
      price: 15.99,
      desc: 'Authentic Kachchi Dum Biryani: Long-grain basmati rice and marinated bone-in chicken slow-cooked sealed with dough, saffron, and mint.',
      emoji: '🍚',
      image_url: null,
      available: true,
      modifier_groups: [biryaniSidesMod, spiceLevelMod],
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_VIJAYAWADA_BIRYANI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_BIRYANI',
      name: 'Vijayawada Special Boneless Chicken Biryani',
      price: 16.99,
      desc: 'Aromatic biryani rice crowned with spicy Andhra-style boneless Chicken 65 and fried cashew nuts.',
      emoji: '🍗',
      image_url: null,
      available: true,
      modifier_groups: [biryaniSidesMod, spiceLevelMod],
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_LAMB_BIRYANI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_BIRYANI',
      name: 'Royal Lamb Dum Biryani',
      price: 17.99,
      desc: 'Tender boneless lamb pieces slow-cooked with aged basmati rice, caramelized onions, and royal garam masala.',
      emoji: '🥩',
      image_url: null,
      available: true,
      modifier_groups: [biryaniSidesMod, spiceLevelMod],
      sort_order: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_GOAT_BIRYANI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_BIRYANI',
      name: 'Hyderabadi Goat Dum Biryani',
      price: 16.99,
      desc: 'Bone-in young goat pieces slow-cooked with basmati rice, fresh mint, coriander, and kewra essence.',
      emoji: '🐐',
      image_url: null,
      available: true,
      modifier_groups: [biryaniSidesMod, spiceLevelMod],
      sort_order: 4,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_EGG_BIRYANI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_BIRYANI',
      name: 'Spiced Egg Biryani',
      price: 13.99,
      desc: 'Hard-boiled eggs browned in spices and layered with fragrant biryani rice, served with raitha and salan.',
      emoji: '🥚',
      image_url: null,
      available: true,
      modifier_groups: [biryaniSidesMod, spiceLevelMod],
      sort_order: 5,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_VEG_DUM_BIRYANI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_BIRYANI',
      name: 'Vegetable Dum Biryani',
      price: 13.99,
      desc: 'Assortment of fresh garden vegetables, paneer cubes, and basmati rice slow-cooked with aromatic whole spices.',
      emoji: '🥦',
      image_url: null,
      available: true,
      modifier_groups: [biryaniSidesMod, spiceLevelMod],
      sort_order: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },

    // 🫓 Fresh Tandoori Breads
    {
      _id: 'MI_VINDU_GARLIC_NAAN',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_BREADS',
      name: 'Garlic Butter Naan',
      price: 4.99,
      desc: 'Hand-stretched leavened flatbread baked against the clay tandoor wall, topped with fresh crushed garlic, cilantro, and pure butter.',
      emoji: '🧄',
      image_url: null,
      available: true,
      modifier_groups: [naanButterMod],
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_PLAIN_NAAN',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_BREADS',
      name: 'Classic Tandoori Naan',
      price: 2.99,
      desc: 'Soft, fluffy, freshly baked traditional Indian flatbread.',
      emoji: '🫓',
      image_url: null,
      available: true,
      modifier_groups: [naanButterMod],
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CHEESE_NAAN',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_BREADS',
      name: 'Gooey Cheese Naan',
      price: 5.49,
      desc: 'Freshly baked naan stuffed with melted mozzarella and paneer cheese.',
      emoji: '🧀',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CHILI_GARLIC_NAAN',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_BREADS',
      name: 'Bullet Chili Garlic Naan',
      price: 5.49,
      desc: 'Spicy naan flatbread studded with minced hot green chilies and roasted garlic.',
      emoji: '🌶️',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 4,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_ONION_KULCHA',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_BREADS',
      name: 'Onion Kulcha',
      price: 4.99,
      desc: 'Soft leavened flatbread stuffed with finely diced spiced onions, cilantro, and carom seeds.',
      emoji: '🧅',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 5,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_TANDOORI_ROTI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_BREADS',
      name: 'Whole Wheat Tandoori Roti',
      price: 2.99,
      desc: 'Wholesome unleavened whole wheat flatbread cooked in the clay oven.',
      emoji: '🫓',
      image_url: null,
      available: true,
      modifier_groups: [naanButterMod],
      sort_order: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },

    // 🥢 Indo-Chinese Specials
    {
      _id: 'MI_VINDU_VEG_FRIED_RICE',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_INDOCHINESE',
      name: 'Vegetable Hakka Fried Rice',
      price: 11.99,
      desc: 'Wok-tossed basmati rice with finely shredded cabbage, carrots, spring onions, and light soy seasoning.',
      emoji: '🥢',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CHICKEN_FRIED_RICE',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_INDOCHINESE',
      name: 'Chicken & Egg Fried Rice',
      price: 13.99,
      desc: 'Wok-fried rice with tender chicken breast, scrambled eggs, scallions, and savory oriental spices.',
      emoji: '🍗',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_VEG_HAKKA_NOODLES',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_INDOCHINESE',
      name: 'Vegetable Hakka Noodles',
      price: 11.99,
      desc: 'Stir-fried wheat noodles with crunchy bell peppers, shredded vegetables, and spicy chili-garlic oil.',
      emoji: '🍜',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_CHICKEN_HAKKA_NOODLES',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_INDOCHINESE',
      name: 'Chicken Hakka Noodles',
      price: 13.99,
      desc: 'Wok-tossed egg noodles with tender chicken strips, green cabbage, scallions, and spicy Indo-Chinese sauce.',
      emoji: '🍜',
      image_url: null,
      available: true,
      modifier_groups: [spiceLevelMod],
      sort_order: 4,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },

    // 🍨 Desserts & Beverages
    {
      _id: 'MI_VINDU_GULAB_JAMUN',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DESSERTS_BEV',
      name: 'Warm Gulab Jamun (3 pcs)',
      price: 5.99,
      desc: 'Warm, golden milk-solid dumplings soaked in aromatic cardamom and rosewater sugar syrup.',
      emoji: '🍯',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 1,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_RASMALAI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DESSERTS_BEV',
      name: 'Royal Rasmalai (2 pcs)',
      price: 6.49,
      desc: 'Delicate cottage cheese patties immersed in chilled clotted saffron milk, garnished with crushed pistachios and almonds.',
      emoji: '🥛',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 2,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_MANGO_KULFI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DESSERTS_BEV',
      name: 'Alphonso Mango Kulfi',
      price: 5.99,
      desc: 'Traditional slow-reduced Indian ice cream made with real Alphonso mango pulp and cardamom.',
      emoji: '🍦',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 3,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_MANGO_LASSI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DESSERTS_BEV',
      name: 'Fresh Mango Lassi',
      price: 4.99,
      desc: 'Thick, refreshing creamy yogurt drink blended with sweet Alphonso mangoes and a touch of green cardamom.',
      emoji: '🥭',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 4,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_MASALA_CHAI',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DESSERTS_BEV',
      name: 'Freshly Brewed Masala Chai',
      price: 3.99,
      desc: 'Slow-simmered Assam black tea with whole milk, crushed ginger, cardamom, cloves, and cinnamon.',
      emoji: '☕',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 5,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      _id: 'MI_VINDU_MADRAS_COFFEE',
      restaurant_id: VINDU_RES_ID,
      category_id: 'CAT_VINDU_DESSERTS_BEV',
      name: 'South Indian Filter Coffee',
      price: 4.49,
      desc: 'Traditional South Indian chicory-infused decoction frothed with boiling whole milk.',
      emoji: '☕',
      image_url: null,
      available: true,
      modifier_groups: [],
      sort_order: 6,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];

  // 5. Replace categories and menu items for Vindu
  db.menu_categories = (db.menu_categories || []).filter((c: any) => c.restaurant_id !== VINDU_RES_ID);
  db.menu_categories.push(...categories);

  db.menu_items = (db.menu_items || []).filter((i: any) => i.restaurant_id !== VINDU_RES_ID);
  db.menu_items.push(...items);

  // 6. Ensure default floor tables exist for Vindu
  const existingTables = (db.tables || []).filter((t: any) => t.restaurant_id === VINDU_RES_ID);
  if (existingTables.length === 0) {
    db.tables = db.tables || [];
    for (let t = 1; t <= 15; t++) {
      db.tables.push({
        _id: `TBL_VINDU_${t}`,
        restaurant_id: VINDU_RES_ID,
        number: t,
        label: `Table ${t}`,
        capacity: t <= 4 ? 2 : (t <= 10 ? 4 : 6),
        active: true,
        created_at: new Date().toISOString(),
      });
    }
  }

  // 7. Write to Local JSON
  fs.writeFileSync(DB_FILE, JSON.stringify(db, null, 2), 'utf8');
  console.log(`✅ Saved ${categories.length} Categories and ${items.length} Menu Items for Vindu to local DB file.`);

  // 8. Sync with MongoDB Atlas if initialized
  try {
    for (const cat of categories) {
      await MultiTenantDbService.createMenuCategory(cat).catch(() => {});
    }
    for (const it of items) {
      await MultiTenantDbService.createMenuItem(it).catch(() => {});
    }
    console.log('✅ MongoDB Atlas direct sync completed.');
  } catch (syncErr: any) {
    console.warn('Atlas sync note:', syncErr.message);
  }

  console.log('\n🎉 Vindu Indian Cuisine Menu Seeding Completed Successfully! 🚀');
}

seedVinduMenu().catch(console.error);
